// This file is generated by Convex and will be replaced
// For development purposes, we'll create a minimal implementation

export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
} from "convex/server"
export type { QueryCtx, MutationCtx, ActionCtx } from "convex/server"
