export interface UserMemory {
  id: string
  userId: string
  projectId?: string
  content: string
  createdAt: Date
  updatedAt: Date
  isAutoGenerated: boolean
  category?: "preference" | "fact" | "instruction" | "style"
}

export interface MemorySuggestion {
  id: string
  content: string
  confidence: number
  context: string
  dismissed: boolean
}

export interface RAGResult {
  id: string
  content: string
  chatId: string
  timestamp: Date
  relevanceScore: number
  snippet: string
}

export interface CreateMemoryData {
  content: string
  projectId?: string
  category?: UserMemory["category"]
}
