name: Auto-merge approved PRs

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.review.state == 'approved' ||
      (github.event.check_suite.conclusion == 'success' && github.event.check_suite.pull_requests[0]) ||
      (github.event.state == 'success' && github.event.branches[0].name != github.event.repository.default_branch)
    
    steps:
      - name: Auto-merge PR
        uses: pascalgn/auto-merge-action@v0.15.6
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "auto-merge,!do-not-merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_FORKS: "false"
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000
          UPDATE_LABELS: "auto-merge"
          UPDATE_METHOD: "rebase"