name: Dependency Review

on:
  pull_request:
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on critical vulnerabilities
          fail-on-severity: critical
          
          # Warn on high vulnerabilities
          warn-only: true
          
          # Check licenses
          license-check: true
          deny-licenses: |
            AGPL-3.0
            GPL-3.0
            LGPL-3.0
          
      - name: Check for known vulnerabilities
        run: |
          npx audit-ci --high --report-type summary